### ISSUE TITLE
Manifest should contain a version field

### ISSUE THREAD

**Issue by mtdcr** [tuxuser/abfallapi_jumomind_ha#1]
Thank you for your work, @tuxuser!

Home Assistant wants me to report the following warning:

> No 'version' key in the manifest file for custom integration 'abfallapi_jumomind'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'abfallapi_jumomind'

Would you mind adding a version field to [manifest.json](https://github.com/tuxuser/abfallapi_jumomind_ha/blob/master/custom_components/abfallapi_jumomind/manifest.json)? It needs to have a format understood by [AwesomeVersion](https://github.com/ludeeus/awesomeversion#readme).

See also: https://developers.home-assistant.io/docs/creating_integration_manifest/#version

**Comment by tuxuser** [comment]
Done
