### ISSUE TITLE
Add Detmold as Service

### ISSUE THREAD

**Issue by Gambrius** [tuxuser/abfallapi_jumomind_ha#6]
Hallo,

I love your tool, but we moved from a supported city to Detmold.
Could you add the Detmold data to this service?

You can find the information here:
https://abfuhrkalender.detmold.de/index.php

They have a download for an .ics file handled through a php url:
https://abfuhrkalender.detmold.de/icsmaker.php?strid=821&year=2022

The "strid" is the "Street id"
"year" can be either this or the upcoming year.

Thank you for your support.

**Comment by tuxuser** [comment]
Hey, sorry, this is out of scope for this project.

This plugin specifically targets cities that use the jumomind API (jumomind.com/mmapp/api.php?r=cities&city_id=&area_id=)

Best would be to ask in the home assistant forum, if such a plugin exists.

Cheers
